<a href="https://colab.research.google.com/github/TheDodoDev/PyTorch-Notes/blob/main/00_PyTorch_Fundamentals_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##00. PyTorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
##Important Imports
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7);
scalar

tensor(7)

In [ ]:
# Finds number of dimensions of scalar
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7, 7])
vector

tensor([7, 7, 7])

In [ ]:
# Vectors are rank one tensors (1-dim)
vector.ndim

1

In [ ]:
# Gets size of numbers in vector
vector.shape

torch.Size([3])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 5]],
                       [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 5]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[1]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

Random tensors are important because many neural networks learn through adjusting tensors initially full of random numbers to better represent the data.


In [ ]:
# Creating random tensors of size (3, 4)
random_tensor = torch.rand(3, 4);
random_tensor


tensor([[0.4962, 0.8450, 0.0551, 0.7765],
        [0.3156, 0.6536, 0.4495, 0.2205],
        [0.0742, 0.4760, 0.5244, 0.1046]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [ ]:
# Create a tensor of all zeroes
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# Default data type of tensors is float
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange
zero_to_nine = torch.arange(start=0, end=10, step=2)
zero_to_nine

tensor([0, 2, 4, 6, 8])

In [ ]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=zero_to_nine)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor Datatypes
**Note:**  Tensor datatypes is one of the 3 big errors with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what data type is the tensor (e.g float, double, half)
                               device="cpu", # what device the tensor is stored on (e.g cuda(gpu), cpu)
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting attributes from tensors

1. `tensor.dtype` - gets datatype from a tensor
2. `tensor.shape` - gets shape from a tensor
3. `tensor.device` - gets device from a tensor



In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4);
some_tensor

tensor([[1.7888e-01, 9.8032e-01, 3.4142e-01, 3.1000e-04],
        [4.1570e-01, 2.8866e-01, 1.5968e-01, 3.9208e-01],
        [7.6247e-01, 7.6656e-01, 1.3793e-01, 4.6141e-01]])

In [ ]:
# Find out details about some tensor
print(some_tensor);
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[1.7888e-01, 9.8032e-01, 3.4142e-01, 3.1000e-04],
        [4.1570e-01, 2.8866e-01, 1.5968e-01, 3.9208e-01],
        [7.6247e-01, 7.6656e-01, 1.3793e-01, 4.6141e-01]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Tensor Operations

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10 from a tensor
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])


### Matrix multiplication

There are two main ways to perform multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot products)

There are 2 main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2) `won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` will have a shape of `(2, 2)`
* `(3, 2) @ (2, 3)` will have a shape of `(3, 3)`


In [ ]:
# Element wise multiplication
print(tensor, "*", tensor, "=", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 49 µs, sys: 7 µs, total: 56 µs
Wall time: 60.8 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])
torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it's an alias for torch.matmul)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
# Matrix multiplication operation works when tensor_B is transposed
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.mm(tensor_B.T, tensor_A)

tensor([[ 76, 100],
        [103, 136]])

## Finding min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10);
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() function requres a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the min value with argmin()
x.argmin()

tensor(0)

In [ ]:
# Find the position in tensor that has max value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing, and unsqueezing tensors

* **Reshaping** - reshapes an input tensor to a defined shape
* **View** - return a view of an input tensor of certain shape but keep same memory as original tensor
* **Stacking** - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* **Squeeze** - removes all `1` dimensions from a tensor
* **Unsqueeze** - add a `1` dimension to a target tensor
* **Permute** - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [ ]:
# Add an extra dimension - reshaped tensor has to have same size
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# Change the view
z = x.view(9, 1)
z, z.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Changing z changes x (because a view of a tensor shares same memory as original)
z[8, :] = 12
z, x

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [12.]]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 12.]))

In [ ]:
# Stack tensors on top
x_stacked = torch.stack([x, x, x, x], dim=0) #dim = 0 - vstack, dim = 1 -  hstack
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [12., 12., 12., 12.]])

In [ ]:
# Squeeze tensor - removes all single dimensions
y = torch.rand(1, 2, 4, 1)
print("Original Tensor: ", y)
print("Original Shape: ", y.shape)

y_squeezed = torch.squeeze(y)
print("Squeezing y...")
print("-------------------------------")
print("Squeezed Tensor: ", y_squeezed)
print("Squeezed Shape: ", y_squeezed.shape)

Original Tensor:  tensor([[[[0.3173],
          [0.1753],
          [0.1288],
          [0.3672]],

         [[0.1264],
          [0.6993],
          [0.0153],
          [0.5122]]]])
Original Shape:  torch.Size([1, 2, 4, 1])
Squeezing y...
-------------------------------
Squeezed Tensor:  tensor([[0.3173, 0.1753, 0.1288, 0.3672],
        [0.1264, 0.6993, 0.0153, 0.5122]])
Squeezed Shape:  torch.Size([2, 4])


In [ ]:
# Unsqueeze tensor
y_unsqueezed = torch.unsqueeze(y_squeezed, 0)
y_unsqueezed, y_unsqueezed.shape

(tensor([[[0.3173, 0.1753, 0.1288, 0.3672],
          [0.1264, 0.6993, 0.0153, 0.5122]]]),
 torch.Size([1, 2, 4]))

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
y_permuted = y.permute((3, 2, 1, 0))
y_permuted, y_permuted.shape

(tensor([[[[0.3173],
           [0.1264]],
 
          [[0.1753],
           [0.6993]],
 
          [[0.1288],
           [0.0153]],
 
          [[0.3672],
           [0.5122]]]]),
 torch.Size([1, 4, 2, 1]))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
# Create a tensor
import torch
x = torch.arange(0, 20).reshape(2, 2, 5)
x, x.shape

(tensor([[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9]],
 
         [[10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]]]),
 torch.Size([2, 2, 5]))

In [ ]:
# Indexing tensor
x[0]

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Indexing middle dimension
x[0, 0]

tensor([0, 1, 2, 3, 4])

In [ ]:
# Indexing 3rd dimension
x[0, 0, 0]

tensor(0)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[ 1,  6],
        [11, 16]])

In [ ]:
# Get all values of 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([ 6, 16])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library. As a result of NumPy's popularity, PyTorch can interact with NumPy for better integration and extensive use.

* Convert NumPy data to PyTorch tensor -> `torch.from_numpy(ndarray)`
* Convert PyTorch tensor to NumPy data -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # copies NumPy default type of float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # copies PyTorch default type of float32
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibiliy (trying to take random out of random)

Neural Network Learning Process
1. `Start with random numbers`
2. `Tensor Operations`
3. `Update random numbers to try and make them better representations of the data`
4. `Repeat`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**. Essentially what the random seed does is "flavor" the randomness


In [ ]:
# Create 2 random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1647, 0.7969, 0.3933, 0.3017],
        [0.4331, 0.9648, 0.4008, 0.4472],
        [0.8590, 0.6162, 0.1408, 0.3330]])
tensor([[0.2869, 0.2291, 0.4187, 0.2459],
        [0.0288, 0.9639, 0.7298, 0.9050],
        [0.4894, 0.2893, 0.5532, 0.2281]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
RANDOM_SEED = 1234

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) #Set seed before each `torch.rand()` method
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681],
        [0.6738, 0.3315, 0.7837, 0.5631]])
tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681],
        [0.6738, 0.3315, 0.7837, 0.5631]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a bit of setup and requires the investment of purchasing a GPU, there's lots of options (https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/)
3. Use cloud computing - GCP, AWS, Azure, these services allows you to rent computers on the cloud and access them

Refer to PyTorch setup documentation for setting up CUDA for 2, 3


In [ ]:
!nvidia-smi

Sun Jun 22 18:42:14 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch

torch.cuda.is_available()

True

For PyTorch since it is capable of running on both GPU or CPU, it is best practice to set up device agnostic code: https://docs.pytorch.org/docs/stable/notes/cuda.html#best-practices

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count the number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors and models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# Move tensor back to CPU to transform tensor to NumPy
tensor_back_to_cpu = tensor_on_gpu.cpu()
tensor_back_to_cpu.numpy()

array([1, 2, 3])