<a href="https://colab.research.google.com/github/TheDodoDev/PyTorch-Notes/blob/main/00_PyTorch_Fundamentals_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##00. PyTorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
##Important Imports
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7);
scalar

tensor(7)

In [3]:
# Finds number of dimensions of scalar
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7, 7])
vector

tensor([7, 7, 7])

In [6]:
# Vectors are rank one tensors (1-dim)
vector.ndim

1

In [7]:
# Gets size of numbers in vector
vector.shape

torch.Size([3])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 5, 5]],
                       [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 5]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 3, 3])

In [15]:
TENSOR[1]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

Random tensors are important because many neural networks learn through adjusting tensors initially full of random numbers to better represent the data.


In [16]:
# Creating random tensors of size (3, 4)
random_tensor = torch.rand(3, 4);
random_tensor


tensor([[0.7795, 0.9897, 0.8940, 0.7274],
        [0.9951, 0.1898, 0.3276, 0.3149],
        [0.4333, 0.0319, 0.5577, 0.6797]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [19]:
# Create a tensor of all zeroes
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
# Default data type of tensors is float
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# Use torch.arange
zero_to_nine = torch.arange(start=0, end=10, step=2)
zero_to_nine

tensor([0, 2, 4, 6, 8])

In [23]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=zero_to_nine)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor Datatypes
**Note:**  Tensor datatypes is one of the 3 big errors with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what data type is the tensor (e.g float, double, half)
                               device="cpu", # what device the tensor is stored on (e.g cuda(gpu), cpu)
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting attributes from tensors

1. `tensor.dtype` - gets datatype from a tensor
2. `tensor.shape` - gets shape from a tensor
3. `tensor.device` - gets device from a tensor



In [27]:
# Create a tensor
some_tensor = torch.rand(3, 4);
some_tensor

tensor([[0.3397, 0.4312, 0.7193, 0.7587],
        [0.9111, 0.4518, 0.5298, 0.3000],
        [0.4613, 0.0562, 0.7638, 0.3287]])

In [33]:
# Find out details about some tensor
print(some_tensor);
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3397, 0.4312, 0.7193, 0.7587],
        [0.9111, 0.4518, 0.5298, 0.3000],
        [0.4613, 0.0562, 0.7638, 0.3287]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Tensor Operations

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [34]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
# Subtract 10 from a tensor
tensor - 10

tensor([-9, -8, -7])

In [51]:
# Try out PyTorch in-built functions
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])


### Matrix multiplication

There are two main ways to perform multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot products)

There are 2 main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2) `won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` will have a shape of `(2, 2)`
* `(3, 2) @ (2, 3)` will have a shape of `(3, 3)`


In [53]:
# Element wise multiplication
print(tensor, "*", tensor, "=", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [59]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 280 µs, sys: 13 µs, total: 293 µs
Wall time: 239 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [66]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])
torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it's an alias for torch.matmul)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [64]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [71]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [70]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [73]:
# Matrix multiplication operation works when tensor_B is transposed
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [75]:
torch.mm(tensor_B.T, tensor_A)

tensor([[ 76, 100],
        [103, 136]])